#!/usr/bin/env ruby

require_relative 'lib/install_swiftlint'
require_relative 'lib/install_sourcery'
require_relative 'lib/installers'

# Install local binaries in ./bin directory
install_swiftlint
install_sourcery

# Install CI environment dependencies
# proselint is a dependency needed by danger-prose plugin.
pip_install "proselint" if running_on_ci?

# Install Ruby gems
bundle_install if File.exist?("Gemfile")

# TODO brew install libressl

# Install dependencies and build
# TODO check if docker is avaiable
# build docker images
#   docker build -t botengine-build -f Dockerfile-build
#   docker build -t botengine .
`swift build`
`swift package generate-xcodeproj` # TODO only do this if running on macOS

puts ""
puts " → You are ready to rock!!!"
puts "\tExecute 'open BotEngine.xcodeproj' and start hacking!"
puts ""
